#!/bin/bash
ver=2.15
# Convention : les variables en minuscules, les fonctions en majuscules.
# Par défaut le script unalias toutes les commandes utilisées pour éviter des comportements qu'il ne peut prévoir
# le script détecte s'il est lancé en arrière plan (dans ce cas, la variable terminal vaut dumb)
#################################################
# Copyright OLIVIER LORILLU                     #
# ce script est sous license GPL                #
# https://www.gnu.org/licenses/gpl.html         #
#################################################
set -euo pipefail
cmdline="$*" 				# arguments de la ligne de commande
scriptfullname="$0" 		# chemin complet du script
scriptname="${0##*/}" 		# équivalent à basename $0, mais en pur bash.

# improve post-upgrade-message to be quicker.

################################################# flatpak COMMANDS ##############################################################
FPK_CHECKUPDCMD() {
	if [ "$silent" = "yes"  ]; then
		# en mode pseudosilencieux je n'affiche rien, je stocke les erreurs et la liste des upd et je met un spinner d'attente
		{ trap STOP-SPINNER EXIT && START-SPINNER; }
			# shellcheck disable=SC2024
			$flatpak update >"$listtmpFP" 2>>"$logerrorFP" || true
		{ STOP-SPINNER && echo "terminée."; }
	else
		# en mode normal, j'affiche tout en gris, je stocke les erreurs et la liste des upd (nettoyée)")
		echo -e "$gris"
		# shellcheck disable=SC2024
		$flatpak update > >(tee "$listtmpFP") 2> >(tee -a "$logerrorFP" >&2) || true
		echo -ne "$reinit"
	fi
	cat "$listtmpFP" >> "$logFP"
	sed -i '/^[[:space:]]*[0-9]\+\./!d' "$listtmpFP"
	return 0
}
#-------------------------------------------------------------------------------------------
FPK_UPDCMD() {
	if [ "$silent" = "yes"  ]; then
		{ trap STOP-SPINNER EXIT && START-SPINNER; }
			# shellcheck disable=SC2024
			$flatpak -y update >>"$logFP" 2>>"$logerrorFP" || true
		{ STOP-SPINNER && echo "terminée."; }
	else
		echo -e "$gris"
		# shellcheck disable=SC2024
		$flatpak -y update > >(tee -a "$logFP") 2> >(tee -a "$logerrorFP" >&2) || true
		echo -ne "$reinit"
	fi
	return 0
}
#-------------------------------------------------------------------------------------------


################################################# dnf COMMANDS #################################################################
DNF_CLEANCMD() { # nettoyage complet du cache
	local tmp="$HOME/.cache/file.tmp"
	SUDOPASS
	if [ "$silent" = "yes"  ]; then
		# shellcheck disable=SC2024
		sudo $dnf clean all -q >>"$log" 2>>"$logerror" || true
	else
		echo -e "$gris"
		# shellcheck disable=SC2024
		sudo $dnf clean all 2>&1 | tee "$tmp" || true
		echo -ne "$reinit"
		tee -a "$log" "$logerror" < "$tmp" > /dev/null
		rm -f "$tmp"
	fi
	unset tmp
	return 0
}
#-------------------------------------------------------------------------------------------
DNF_CACHEUPDCMD() { # création du cache
	local tmp="$HOME/.cache/file2.tmp"
	SUDOPASS
	if [ "$silent" = "yes"  ]; then
		{ trap STOP-SPINNER EXIT && START-SPINNER; }
			# shellcheck disable=SC2024
			sudo $dnf makecache -q >>"$log" 2>>"$logerror" || true
		{ STOP-SPINNER && echo "terminée."; }
	else
		echo -e "$gris"
		# shellcheck disable=SC2024
		sudo $dnf makecache 2>&1 | tee "$tmp" || true
		echo -ne "$reinit"
		tee -a "$log" "$logerror" < "$tmp" > /dev/null
		rm -f "$tmp"
	fi
	unset tmp
	return 0
}
#-------------------------------------------------------------------------------------------
DNF_CHECKUPDCMD() { # vérification de la présence de mise à jour
	SUDOPASS
	if [ "$silent" = "yes"  ]; then
		# en mode pseudosilencieux je n'affiche rien, je stocke les erreurs et la liste des upd et je met un spinner d'attente
		{ trap STOP-SPINNER EXIT && START-SPINNER; }
			if [ "$changelog" = "" ]; then
				# shellcheck disable=SC2024
				sudo $dnf check-update -q >"$listtmp" 2>>"$logerror" || true
			else
				# shellcheck disable=SC2024
				sudo $dnf check-update --changelogs -q >"$listtmp" 2>>"$logerror" || true
			fi
		{ STOP-SPINNER && echo "terminée."; }
	else
		# en mode normal, j'affiche tout en gris, je stocke les erreurs et la liste des upd (nettoyée)")
		echo -e "$gris"
		if [ "$changelog" = "" ]; then
			# shellcheck disable=SC2024
			sudo $dnf check-update > >(tee "$listtmp" | sed '/^$/d') 2> >(tee -a "$logerror" >&2) || true
		else
			# shellcheck disable=SC2024
			sudo $dnf check-update --changelogs > >(tee "$listtmp" | sed '/^$/d') 2> >(tee -a "$logerror" >&2) || true
		fi
		echo -ne "$reinit"
	fi
	sed -i '/.*|.*|.*|.*/d;/passage de paquets en obsolètes/d;/Obsoleting Packages/d;/^$/d' "$listtmp"
	sed '/^Changelogs/ {x;p;x}' "$listtmp" >> "$log"
	return 0
}
#-------------------------------------------------------------------------------------------
DNF_UPDATECMD() { # mise à jour directe
	SUDOPASS
	if [ "$silent" = "yes"  ]; then
		{ trap STOP-SPINNER EXIT && START-SPINNER; }
			# shellcheck disable=SC2024
			sudo $dnf -y upgrade >>"$log" 2>>"$logerror" || true
		{ STOP-SPINNER && echo "terminés."; }
	else
		echo -e "$gris"
		# shellcheck disable=SC2024
		sudo $dnf -y upgrade > >(tee -a "$log") 2> >(tee -a "$logerror" >&2) || true
		echo -ne "$reinit"
	fi
	return 0
}
#-------------------------------------------------------------------------------------------
DNF_OFF-UPDATECMD() { # mise à jour offline - download pkgs
	SUDOPASS
	if [ "$silent" = "yes"  ]; then
		{ trap STOP-SPINNER EXIT && START-SPINNER; }
			# shellcheck disable=SC2024
			sudo $dnf -y offline-upgrade download >>"$log" 2>>"$logerror" || true
		{ STOP-SPINNER && echo "terminé."; }
	else
		echo -e "$gris"
		# shellcheck disable=SC2024
		sudo $dnf -y offline-upgrade download > >(tee -a "$log") 2> >(tee -a "$logerror" >&2) || true
		echo -ne "$reinit"
	fi
	return 0
}
#-------------------------------------------------------------------------------------------
DNF_OFF-REBOOTCMD() { # mise à jour offline - reboot
	SUDOPASS
	if [ "$poweroff" = "yes" ]; then
		# shellcheck disable=SC2024
		sudo $dnf offline-upgrade -y reboot --poweroff >>"$log" 2>>"$logerror" || true
	else
		# shellcheck disable=SC2024
		sudo $dnf offline-upgrade -y reboot >>"$log" 2>>"$logerror" || true
	fi
	exit 0
}
#-------------------------------------------------------------------------------------------
DNF_OFF-CLEANCMD() { # mise à jour offline - clean pkgs
	SUDOPASS
	if [ "$silent" = "yes"  ]; then
		# shellcheck disable=SC2024
		sudo $dnf offline-upgrade clean >>"$log" 2>>"$logerror" || true
	else
		echo -ne "$gris"
		# shellcheck disable=SC2024
		sudo $dnf offline-upgrade clean > >(tee -a "$log") 2> >(tee -a "$logerror" >&2) || true
		echo -ne "$reinit"
	fi
}
#-------------------------------------------------------------------------------------------
DNF_UPGRADE-REBOOTCMD() { # mise à jour offline - reboot
	SUDOPASS
	if [ "$poweroff" = "yes" ]; then
		# shellcheck disable=SC2024
		sudo $dnf system-upgrade -y reboot --poweroff >>"$log" 2>>"$logerror" || true
	else
		# shellcheck disable=SC2024
		sudo $dnf system-upgrade -y reboot >>"$log" 2>>"$logerror" || true
	fi
	exit 0
}
#-------------------------------------------------------------------------------------------
DNF_UPGRADE-CLEANCMD() { # mise à jour offline - clean pkgs
	SUDOPASS
	if [ "$silent" = "yes"  ]; then
		# shellcheck disable=SC2024
		sudo $dnf system-upgrade clean >>"$log" 2>>"$logerror" || true
	else
		echo -ne "$gris"
		# shellcheck disable=SC2024
		sudo $dnf system-upgrade clean > >(tee -a "$log") 2> >(tee -a "$logerror" >&2) || true
		echo -ne "$reinit"
	fi
}
#-------------------------------------------------------------------------------------------
DNF_UPGRADECMD() { # mise à niveau
	SUDOPASS
	local -i TARGET
	TARGET=$1
	echo -ne "$gris"
	if [[ "$dnfver" == "dnf4" ]]; then
		# shellcheck disable=SC2024
		sudo $dnf -y system-upgrade download --allowerasing --setopt=module_platform_id=platform:f$TARGET --releasever=$TARGET > >(tee -a "$log") 2> >(tee -a "$logerror" >&2) || true
	else
		# shellcheck disable=SC2024
		sudo $dnf -y system-upgrade download --setopt=module_platform_id=platform:f$TARGET --releasever=$TARGET > >(tee -a "$log") 2> >(tee -a "$logerror" >&2) || true
	fi
	echo -ne "$reinit"
}
#-------------------------------------------------------------------------------------------
DNF_CHECK_OFFLINE_UPGRADE_READY() {
    SUDOPASS
    local dnf_file=""
   	if [[ "$dnfver" == "dnf4" ]]; then
    	dnf_file="/var/lib/dnf/system-upgrade/system-upgrade-transaction.json"
    else
    	dnf_file="/usr/lib/sysimage/libdnf5/offline/transaction.json"
    fi
    if sudo ls "$dnf_file" &>/dev/null; then # je teste la présence du fichier en root car $USER n'a pas les droits
        return 0
    else
    	return 1
    fi
}
################################################################################################################################



################################################################################################################################
#            AUTRES SOUS-ROUTINES DU SCRIPT                                                                                    #
################################################################################################################################
EXISTS() {
	unalias "$1" >/dev/null 2>&1 || true
	command -v "$1" >/dev/null 2>&1
}
################################################################################################################################
CECHO() { # script to write something to stdout in colors
   	local message=$1
   	local color=$2
   	local nonewline=$3
   	if [ "$terminal" != "dumb" ]; then
  		echo -e "$nonewline" "$color$message$reinit" || true
   	else
  		echo "$nonewline" "$message" || true
   	fi
   	return 0
}
################################################################################################################################
HOSTNAME() {
    host=$(/usr/bin/hostnamectl --transient 2>/dev/null) || true
    [ -n "$host" ] || host=$(/usr/bin/hostname 2>/dev/null) || true
    [ -n "$host" ] || host=$(/usr/bin/uname -n 2>/dev/null) || true
    [ -n "$host" ] || host="unknown"
    return 0
}
################################################################################################################################
CHECK_DNF_VERSION() {
    local version_info=""
    version_info=$($dnf --version 2>/dev/null || echo "unknown")
    if echo "$version_info" | grep -q "4\."; then
        echo "dnf4"
    elif echo "$version_info" | grep -q "5\."; then
        echo "dnf5"
    else
        echo "Unable to determine DNF version." >> "$bigerror"
        return 1
    fi
}
################################################################################################################################
USE-DNF4() {
	if EXISTS /usr/bin/dnf4; then
		dnf="/usr/bin/dnf4"
		forcednf4="yes"
	else
		CECHO "[WARN]" "$jaune" -n && echo -e " ${gras}${bleu}/usr/bin/dnf4${reinit} n\'existe pas."
		CECHO "[INFO]" "$jaune" -n && echo -e " On utilise ${gras}${bleu}/usr/bin/dnf${reinit}."
	fi
}
################################################################################################################################
USE-DNF5() {
	if EXISTS /usr/bin/dnf5; then
		dnf="/usr/bin/dnf5"
		forcednf5="yes"
	else
		CECHO "[WARN]" "$jaune" -n && echo -e " ${gras}${bleu}/usr/bin/dnf5${reinit} n\'existe pas."
		CECHO "[INFO]" "$jaune" -n && echo -e " On utilise ${gras}${bleu}/usr/bin/dnf${reinit}."
	fi
}
################################################################################################################################
INITCOLOR() {
	if [ "$terminal" = "dumb" ] || [ -z "$terminal" ]; then
		TERM="xterm"
		noir=''
		rouge=''
		vert=''
		jaune=''
		bleu=''
		magenta=''
		cyan=''
		blanc=''
		gris=''
		gras=''
		underline=''
		italic=''
		reinit=''
		GREP_COLORS=''
	else
		export noir='\e[30m'
		export rouge='\e[31m'
		export vert='\e[32m'
		export jaune='\e[33m'
		export cyan='\e[36m'
		export magenta='\e[35m'
		export bleu='\e[34m'
		export blanc='\e[37m'
		export gris='\e[90m'
		export gras='\e[1m'
		export underline='\e[4m'
		export italic='\e[3m'
		export reinit='\e[0m'
		export GREP_COLORS='mt=1;34'
	fi
	return 0
}
################################################################################################################################
PASSWORD_INPUT() { # Fonction pour capturer le mot de passe le stocker dans $password et afficher des *
	local password_ref
	password_ref=""
	local char
	# Désactiver l'affichage des caractères
	stty -echo || return 1
	while IFS= read -r -s -n1 char; do
		# on arrête quand la touche ENTREE est pressée
		if [[ -z $char ]]; then
			break
		fi
		# Si la touche backspace est pressée
		if [[ $char == $'\x7f' ]]; then
		    if [[ ${#password_ref} -gt 0 ]]; then
		    password_ref=${password_ref%?}
		    echo -ne "\b \b"
		    fi
		else
		    password_ref+="$char"
		    echo -n '*'
		fi
	done
	password="$password_ref"
	echo
	stty echo || return 1 # Réactiver l'affichage des caractères
	return 0
}
################################################################################################################################
ENCRYPT-PASS() {
	local pubkey="${privatekey}.pub"
	if EXISTS openssl; then
		# Generate private RSA key in PEM format
		if ! openssl genpkey -algorithm RSA -out "$privatekey" -pkeyopt rsa_keygen_bits:4096 >/dev/null 2>&1; then
			CECHO "[ERR.]" "$rouge" -n && echo "Erreur lors de la génération de la clé privée." | tee -a "$bigerror"
			return 1
		fi
		chmod 600 "$privatekey" || true
		# Generate the associated public key in PEM format
		if ! openssl rsa -in "$privatekey" -pubout -out "$pubkey" >/dev/null 2>&1; then
			CECHO "[ERR.]" "$rouge" -n && echo "Erreur lors de la génération de la clé publique." | tee -a "$bigerror"
			return 1
		fi
		# Encrypt password using the public key and store it
		if ! echo -n "$password" | openssl pkeyutl -encrypt -pubin -inkey "$pubkey" -out "$passwordencrypted" >/dev/null 2>&1; then
			CECHO "[ERR.]" "$rouge" -n && echo "Erreur lors du chiffrement du mot de passe." | tee -a "$bigerror"
			return 1
		fi
	else
		CECHO "[ERR.]" "$rouge" -n && echo -e "Le paquet ${gras}${bleu}openssl${reinit} n'est pas installé." | tee -a "$bigerror"
		return 1
	fi
	return 0
}
################################################################################################################################
DECRYPT-PASS() {
	if EXISTS openssl; then
		# Decrypt the password using the private key and store it in the password variable
		if [ -f "$privatekey" ] && [ -f "$passwordencrypted" ]; then
			if ! password=$(openssl pkeyutl -decrypt -inkey "$privatekey" -in "$passwordencrypted" 2>/dev/null); then
				CECHO "[ERR.]" "$rouge" -n && echo "Erreur lors du déchiffrement du mot de passe." | tee -a "$bigerror"
				return 1
			fi
			return 0
		else
			CECHO "[ERR.]" "$rouge" -n && echo "Clé privée ou fichier chiffré manquant." | tee -a "$bigerror"
			return 1
		fi
	else
		CECHO "[ERR.]" "$rouge" -n && echo -e "Le paquet ${gras}${bleu}openssl${reinit} n'est pas installé." | tee -a "$bigerror"
		return 1
	fi
}
################################################################################################################################
CREATE-CONFIG() {
	local msg=$1
	if ASK-YESNO "" "$vert" " Voulez-vous en $msg un maintenant (oui/non) ? " "$magenta" ""; then
		while true; do
			CECHO "[ACT.]" "$magenta" -n && echo -n " Merci de saisir une adresse email valide : "
			IFS= read -r email
			if IS-VALID-EMAIL "$email"; then
				echo "email=\"${email}\"" > "$config" || return 1
				break
			fi
		done
		CECHO "[ACT.]" "$magenta" -n && echo -n " Merci de saisir le mot de passe de l'utilisateur $(whoami) : "
		PASSWORD_INPUT || true
		if EXISTS openssl; then
			if ASK-YESNO "" "$vert" " Voulez-vous stocker le mot de passe ${gras}chiffré${reinit} (oui/non) ? " "$magenta" ""; then
				if ENCRYPT-PASS; then
					CECHO "[INFO]" "$vert" -n && echo -e " Le mot de passe est stocké chiffré dans ${gras}${bleu}$passwordencrypted${reinit}."
					echo "password=\"***EnCrYpTed***\"" >> "$config" || true
				else
					CECHO "[ERR.]" "$rouge" -n && echo " Le chiffrement du mot de passe a échoué."
					CECHO "[INFO]" "$vert" -n && echo " Le mot de passe est donc stocké en clair."
					echo "password=\"${password}\"" >> "$config" || true
					chmod 600 "$config" || true
				fi
			else
				rm -f "$passwordencrypted" "$privatekey" "$privatekey.pub"
				CECHO "[INFO]" "$vert" -n && echo " Le mot de passe est donc stocké en clair."
				echo "password=\"${password}\"" >> "$config" || true
				chmod 600 "$config" || true
			fi
		else #openssl n'est pas installé, on stocke en clair.
			CECHO "[WARN]" "$jaune" -n
			echo -e " Le paquet ${gras}${bleu}openssl${reinit} n'est pas installé, la fonction de stockage de chiffrement n'est pas disponible."
			rm -f "$passwordencrypted" "$privatekey" "$privatekey.pub"
			CECHO "[INFO]" "$vert" -n && echo " Le mot de passe est donc stocké en clair."
			echo "password=\"${password}\"" >> "$config" || true
			chmod 600 "$config" || return 1
		fi
		{	echo;
			echo "# option -4 : (décommentez ci-dessous pour activer)";
			echo "#forcednf4=\"yes\"";
			echo;
			echo "# option -5 : (décommentez ci-dessous pour activer)";
			echo "#forcednf5=\"yes\"";
			echo;
			echo "# option -L : (décommentez ci-dessous pour activer)";
			echo "#changelog=\"yes\"";
			echo;
			echo "# option -s : (décommentez ci-dessous pour activer) INFO : le mode \"-v\" permet de passer outre ce réglage.";
			echo "#silent=\"yes\"";
			echo;
			echo "# option -F : (décommentez ci-dessous pour activer)";
			echo "#noflatpak=\"yes\"";
			echo;
			echo "# option -l : (décommentez ci-dessous pour activer)";
			echo "#limitlog=\"yes\"";
			echo;
			echo "# option -p : (décommentez ci-dessous pour activer)";
			echo "#poweroff=\"yes\"";
			echo;
			echo "# option -m : (décommentez ci-dessous pour activer) INFO : le mode \"-M\" permet de passer outre ce réglage.";
			echo "#notif_email=\"yes\"";
			echo;
			echo "# option -B : (décommentez ci-dessous pour activer) INFO : le mode \"-b\" permet de passer outre ce réglage.";
			echo "#nocacheupd=\"yes\"";
			echo;
		} >> "$config"
		CECHO "[INFO]" "$vert" -n && echo -e " Fichier ${gras}${bleu}$config${reinit} crée :"
		$bat "$config" || return 1
	else
		CECHO "[INFO]" "$vert" -n && echo -e " Création du fichier ${gras}${bleu}$config${reinit} refusée par l'utilisateur."
	fi
	return 0
}
################################################################################################################################
CHECK() { # contrôle des dépendances - peut être explicitement appelé (option -C) et alors il affiche des infos complémentaires
	local cmdmissing="no"
	local cmd=""
	if [ "$checkdeps" = "yes" ]; then # contrôle explicit
		#CECHO "[INFO]" "$vert" -n && echo -e " $modeCC (${vert}-C${reinit})."
		echo
		PRINTBANNER-CENTERED "CONTRÔLE" "." "$cyan"
	fi
	list2check=("bash" "sudo" "awk" "sed" "tput" "find" "notify-send" "dnf" "getopt")
	for cmd in "${list2check[@]}"; do
		if ! EXISTS "$cmd" ; then
			CECHO "[ERR.]" "$rouge" -n && echo " La commande $cmd est manquante, veuillez l'installer."
			cmdmissing="yes"
		fi
	done

	if [ "$checkdeps" = "yes" ] ; then # contrôle explicit
		if [ -f "$config" ]; then
			CECHO "[INFO]" "$vert" -n && echo -e " Contenu du fichier de configuration :"
			$bat "$config" || true
			CREATE-CONFIG "recréer"
		else
			CECHO "[INFO]" "$vert" -n && echo -ne " Fichier de configuration ${gras}${bleu}$config${reinit} manquant."
			CREATE-CONFIG "créer"
		fi
	fi

	if [ "$cmdmissing" = "yes" ] || [ "$checkdeps" = "yes" ] ; then # commande manquante ou contrôle explicit, on précise les paquets
		nolog="yes" # pour éviter une rotation des logs inutiles.
		echo
		if [ "$cmdmissing" = "yes" ]; then
			CECHO "[WARN]" "$jaune" -n && echo -e " Voici la liste des ${gras}${jaune}paquets requis${reinit} pour que ce script fonctionne :"
		else
			CECHO "[INFO]" "$vert" -n && echo -e " Voici la liste des ${gras}${jaune}paquets requis${reinit} pour que ce script fonctionne :"
		fi
		echo -e "	${gras}${bleu}bash${reinit}, ${gras}${bleu}coreutils${reinit}, ${gras}${bleu}dnf${reinit}, ${gras}${bleu}findutils${reinit}, ${gras}${bleu}gawk${reinit}, ${gras}${bleu}libnotify${reinit}, ${gras}${bleu}ncurses${reinit}, ${gras}${bleu}sed${reinit}, ${gras}${bleu}sudo${reinit} et ${gras}${bleu}util-linux${reinit}."
		CECHO "[INFO]" "$vert" -n && echo -e " Voici la liste des ${gras}${jaune}paquets requis trouvés${reinit} sur ${gras}$host${reinit} :"
		SUDOPASS
		sudo $dnf list --installed | grep --color=always -E '^(bash|coreutils|dnf|findutils|gawk|libnotify|ncurses|sed|sudo|util-linux)\.' | awk '{$NF=""; sub(/[[:space:]]+$/, ""); printf "%-50s %s\n", $1, $2}' || true
		echo

		CECHO "[INFO]" "$vert" -n && echo -e " Voici la liste des ${gras}${jaune}paquets optionnels${reinit} :"
		echo -e "	${gras}${bleu}s-nail${reinit}, ${gras}${bleu}msmtp${reinit} (ou ${gras}${bleu}opensmtpd${reinit}), ${gras}${bleu}openssl${reinit} et ${gras}${bleu}flatpak${reinit}."
		CECHO "[INFO]" "$vert" -n && echo -e " Voici la liste des ${gras}${jaune}paquets optionnels trouvés${reinit} sur ${gras}$host${reinit} :"
		SUDOPASS
		sudo $dnf list --installed | grep --color=always -E '^(s-nail|msmtp|opensmtpd|flatpak|openssl)\.' | awk '{$NF=""; sub(/[[:space:]]+$/, ""); printf "%-50s %s\n", $1, $2}' || true

		[ "$cmdmissing" = "yes" ] && { THE-END "des erreurs" || true ; exit 1 ; }
		[ "$checkdeps" = "yes" ] && { THE-END "succès" || true ; exit 0 ; }
	else
		return 0
	fi
}
################################################################################################################################
UNALIAS() { # on desalias les commandes utilisées pour éviter un comportement imprévu
	local cmd=""
	list2check=("unalias" "mkdir" "printf" "mail" "touch" "sleep" "rm" "cat" "bat" "sed" "head" "awk" "echo" "dnf" \
	"tput" "notify-send" "sudo" "read" "date" "flatpak" "trap" "command" "dbus-send" "source" "getopts" "ls" "stat" "tee" "openssl")

	for cmd in "${list2check[@]}"; do
		unalias "$cmd" >/dev/null 2>&1 || true
	done
	return 0
}
################################################################################################################################
SUDOPASS() {
	if ! sudo -n true 2>/dev/null; then # si sudo a besoin du mot de passe
		if [ -f "$passwordencrypted" ]; then # mot de passe chiffré
			if DECRYPT-PASS; then
				echo "$password" | sudo -S echo -n > /dev/null 2>&1 || true
			else
				CECHO "[WARN]" "$jaune" -n && echo -e " Erreur de déchiffrement du mot de passe de ${gras}$(whoami)${reinit}"
				CECHO "[INFO]" "$vert" -n && echo -e " Vous pourrez lancer ${gras}${bleu}$scriptfullname -C${reinit} pour refaire le chiffrement."
				CECHO "[INFO]" "$vert" -n && echo -e " On poursuit le déroulement de ${gras}${bleu}$scriptname${reinit}."
				if [ "$terminal" != "dumb" ]; then
					CECHO "[ACT.]" "$magenta" -n && echo -ne " Veuillez saisir le mot de passe de ${gras}${bleu}$(whoami)${reinit} (sudo) : "
					PASSWORD_INPUT || return 1
					echo "$password" | sudo -S echo -n > /dev/null 2>&1 || true
				else
					echo " Le déchiffrement du mot de passe a échoué." | tee -a "$bigerror"
					THE-END "des erreurs" || true
					exit 1
				fi
			fi
		else # mot de passe en clair ou encrypté mais le fichier n'existe plus
			if [ "$terminal" = "dumb" ]; then
				if [ -n "$password" ] && [ "$password" != "***EnCrYpTed***" ]; then
					echo "$password" | sudo -S echo -n > /dev/null 2>&1 || true
				else
					echo " Le mot de passe n'est plus stocké. Veuillez relancer $scriptfullname -C pour recréer le fichier de configuration" | tee -a "$bigerror"
					THE-END "des erreurs" || true
					exit 1
				fi
			else
	     		if [ -n "$password" ] && [ "$password" != "***EnCrYpTed***" ]; then # le mdp existe on l'envoie à sudo
					echo "$password" | sudo -S echo -n > /dev/null 2>&1 || trues
				else # le mdp n'existe pas on le demande à l'utilisateur
					CECHO "[WARN]" "$jaune" -n && echo -e " Le mot de passe n'est plus stocké. Il faudra relancer ${gras}${bleu}$scriptfullname -C${reinit} pour recréer le fichier de configuration."
					CECHO "[INFO]" "$vert" -n && echo -e " On poursuit le déroulement de ${gras}${bleu}$scriptname${reinit}."
					CECHO "[ACT.]" "$magenta" -n && echo -ne " Veuillez saisir le mot de passe de ${gras}${bleu}$(whoami)${reinit} (sudo) : "
					PASSWORD_INPUT || return 1
					echo "$password" | sudo -S echo -n > /dev/null 2>&1 || true
				fi
	        fi
		fi
	fi
	return 0
}
################################################################################################################################
COMPTEUR() {
    local duree="$1" # en secondes
    local largeur="$2" # largeur de la barre de progression
    local message_fin="$3" # message final
    local couleur="$4" # couleur de l'ensemble
    local remplissage
    local bar
    local vide
    local temps_restant
    local index

	echo -ne "$couleur"
	for ((index = 0; index <= duree; index++)); do
        remplissage=$((index * largeur / duree))
        bar=$(printf "%-${remplissage}s" "" | tr ' ' '#')  # Filled part
        vide=$(printf "%-$((largeur - remplissage))s" "" | tr ' ' '.')  # Empty part
        temps_restant=$((duree - index))  # Calculate seconds remaining
        if ((temps_restant == 0)); then
        	echo -ne "\r[${bar}${vide}]              \r"
            echo -ne "$message_fin"
        elif ((temps_restant == 1)); then
            echo -ne "\r[${bar}${vide}] ${temps_restant}s restante   "
        else
            echo -ne "\r[${bar}${vide}] ${temps_restant}s restantes   "
        fi
        sleep 1
    done
    echo -e "$reinit"
}
################################################################################################################################
IS-VALID-EMAIL() {
    local localmail="$1"
    if [[ "$localmail" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; then
        return 0  # Email valide
    else
        return 1  # Email non valide
    fi
}
################################################################################################################################
PRINTBANNER-CENTERED() {
	local msg="$1"
	local fillertype="$2"
	local color="$3"
	[[ $# == 0 ]] && return 1

	declare -i term_cols  # Terminal width
	if [ "$terminal" = "dumb" ]; then
		term_cols=135
	else
		term_cols="$(tput cols)" || return 1
		echo -e -n "$color"
	fi

	declare -i str_len="${#msg}"  # Length of $msg
	[[ $str_len -ge $term_cols ]] && {
		echo "$msg"
		return 0
	}

	declare -i filler_len="$(( (term_cols - str_len) / 2 ))"
	local ch="${fillertype:0:1}"
	local filler=""
	for (( i = 0; i < filler_len; i++ )); do
		filler="${filler}${ch}"
	done

	printf "%s%s%s" "$filler" "$msg" "$filler"
	[[ $(( (term_cols - str_len) % 2 )) -ne 0 ]] && printf "%s" "$ch"
	printf "\n"
	echo -ne "$reinit"
	return 0
}

################################################################################################################################
CLEAR() { # fonction pour effacer le terminal en préservant le scrollback.
	local h
	h="$(tput lines 2>/dev/null)" || h=0

	if [ "$h" -gt 1 ]; then
		until [ "$h" -le 1 ]; do
			printf '\n'
			h=$((h-1))
		done
	fi
	command clear -x || true
	return 0
}

################################################################################################################################
ASK-YESNO() {
#   1. Messsage introductif
#   2. Couleur du type de message introduction : par exemple vert pour [INFO]
#   3. Question à laquelle l utilisateur devra répondre
#   4. Couleur du type accompagnant la question ([ACT.] est le type forcé, pour ACTION).
#   5. Type du message introductif : par exemple [INFO]
# ===>   la fonction retourne le code 0 si la réponse est oui, 1 si non.
	if [ "$terminal" != "dumb" ]; then # le script n'est pas lancé en arrière plan
		local message="$1"
		local color1="$2"
		local question="$3"
		local color2="$4"
		local type="$5"
		local input_string="NA"
		CECHO "$type" "$color1" -n && echo "$message"

		while [ "$input_string" != "oui" ] && [ "$input_string" != "non" ]; do
			CECHO "[ACT.]" "$color2" -n && echo -en "$question"
			IFS= read -r input_string || input_string="non"  # fallback in case of read error
			input_string="${input_string,,}" # je passe tout en minuscules
		done

		if [ "$input_string" = "oui" ]; then
			return 0
		elif [ "$input_string" = "non" ]; then
			return 1
		fi
	else # le script est lancé en arrière plan, la réponse par défaut est non.
		return 1
	fi
}
################################################################################################################################
DATE-ET-HEURE() {
	echo -e "${italic}$(\date '+%T'),$(\date '+%e %B %Y')${reinit}" || true
	return 0
}
################################################################################################################################
START-SPINNER() {
    if [ "$terminal" != "dumb" ]; then
        set +m
        tput civis || true  # Hide cursor, ignore errors if unsupported
        echo -ne "en cours...  ${rouge})"
        local frames=('⠋' '⠙' '⠹' '⠸' '⠼' '⠴' '⠦' '⠧' '⠇' '⠏')
        local index=""
        {
            while : ; do
                for index in "${frames[@]}" ; do
                    echo -en "\b$index"
                    sleep 0.05 || true  # Ignore sleep errors
                done
            done &
        } 2>/dev/null
        spinner_pid=$!
        return 0
    fi
}
################################################################################################################################
STOP-SPINNER() {
    if [ "$terminal" != "dumb" ]; then
        { kill -9 "$spinner_pid" && wait "$spinner_pid" ; } 2>/dev/null || true  # Kill spinner safely
        set -m
        echo -en "\b\b"
        tput cvvis || true  # Show cursor, ignore errors if unsupported
        echo -ne "$reinit"
        return 0
    fi
}
################################################################################################################################
USAGE() {
	CECHO "[INFO]" "$vert" -n && \
	echo -e " utilisation: ${gras}${bleu}${scriptfullname} ${vert}[-h] [-C] [-s] [-v] [-c] [-m] [-M] [-n] [-F] [-R] [-d] [-B] [-b] [-0] [-p] [-L] [-u] [-l] [-D]${reinit}"
	CECHO "[INFO]" "$vert" -n && echo -e " Arguments longs également possibles, voir ${gras}${bleu}${scriptfullname} --help${reinit}."
	return 0
}
################################################################################################################################
DISPLAY-HELP() {
	nolog="yes" # pour éviter une rotation des logs inutiles.
	echo
	PRINTBANNER-CENTERED "AIDE" "." "$cyan"
	echo -ne "$reinit" || true
	cat <<< "$(echo -e "${bleu}${underline}UTILISATION${reinit}
	${gras}${bleu}${scriptfullname} ${vert}[-h] [-C] [-s] [-v] [-c] [-m] [-M] [-n] [-F] [-R] [-d] [-B] [-b] [-0] [-p] [-L] [-u] [-l] [-D]${reinit} (ou arguments longs)

${bleu}${underline}DESCRIPTION${reinit}
	Ce script vérifie si les paquets ${jaune}RPMs${reinit}, et éventuellement ${jaune}FLATPAKs${reinit}, de votre ${jaune}${ID^}${reinit} (${gras}$host${reinit}) nécessitent ${gras}une mise à jour${reinit}.
	Si des nouveaux paquets ${jaune}FLATPAKs${reinit} sont disponibles, ${gras}il procède à la mise à jour immédiatement${reinit}.
	Si des paquets ${jaune}RPMs${reinit} sont disponibles, ${gras}il les télécharge puis redémarre le système pour une mise à jour hors-ligne (plus sûre)${reinit}.
	Le script utilise seulement des commandes ${gras}${bleu}dnf${reinit} et, éventuellement, ${gras}${bleu}flatpak${reinit} (PackageKit non-requis).
	Les erreurs de vérifications et de téléchargements sont gérées.
	Le script doit être lancé par un ${gras}utilisateur normal${reinit} disposant du droit d'élévation de privilèges (${gras}${bleu}sudo${reinit}).

${bleu}${underline}OPTIONS${reinit}
        ${vert}-h, --help           ${reinit}Affiche cette ${jaune}aide${reinit} et quitte,
        ${vert}-C, --checkdeps      ${reinit}Contrôle les dépendances et gère le fichier de configuration ($modeCC),
        ${vert}-s, --silent         ${reinit}Seules les erreurs et la liste de paquets seront affichées ($modeS),
        ${vert}-v, --verbose        ${reinit}Tous les messages sont affichés ($modeV),
        ${vert}-c, --checkonly      ${reinit}Pour vérifier si des mises à jour sont disponibles sans les installer ($modeC),
        ${vert}-m, --notif_mail     ${reinit}Pour envoyer un email si des mises à jour sont disponibles ($modeM),
        ${vert}-M, --nomail         ${reinit}Pour ne pas envoyer un email ($modeMM),
        ${vert}-n, --notify         ${reinit}Pour émettre une notification système si des mises à jour sont disponibles ($modeN),
        ${vert}-F, --noflatpak      ${reinit}Pour désactiver la gestion des ${jaune}FLATPAKs${reinit} ($modeF),
        ${vert}-R, --norpm          ${reinit}Pour désactiver la gestion des ${jaune}RPMs${reinit} ($modeR),
        ${vert}-d, --directrpms     ${reinit}Avec cette option (${gras}non recommandée${reinit}), la mise à jour des ${jaune}RPMs${reinit} sera directe, c'est-à-dire en ligne ($modeD),
        ${vert}-B, --nocacheupd     ${reinit}Avec cette option, le script ne fera pas de mise à jour forcée du cache de ${gras}${bleu}dnf${reinit} ($modeB),
        ${vert}-b, --forcecacheupd  ${reinit}Avec cette option, le script fera une mise à jour forcée du cache de ${gras}${bleu}dnf${reinit} ($modeBB),
        ${vert}-0, --nolog          ${reinit}Pour ne pas créer de log ($mode0),
        ${vert}-D, --deletelog      ${reinit}Pour supprimer tous les logs de ${gras}${bleu}$scriptname${reinit},
        ${vert}-l, --limitlog       ${reinit}Pour ne conserver les logs qu'en cas de mise à jour ($modeLP),
        ${vert}-p, --poweroff       ${reinit}Pour éteindre l'ordinateur après la mise à jour ($modeP),
        ${vert}-L, --changelog      ${reinit}Pour afficher la liste des modifications apportées par les mises à jour des ${jaune}RPMs${reinit} ($modeCL),
        ${vert}-4, --forcednf4      ${reinit}Pour utiliser la commande ${gras}${bleu}dnf4${reinit} ($mode4),
        ${vert}-5, --forcednf5      ${reinit}Pour utiliser la commande ${gras}${bleu}dnf5${reinit} ($mode5),
        ${vert}-u, --distrupgrade   ${reinit}Pour lancer une montée de version du système ($modeU).

${bleu}${underline}FICHIERS${reinit}
	- ${gras}${bleu}$config${reinit} : fichier de configuration de ${gras}${bleu}$scriptname${reinit}.
	- ${gras}${bleu}$datadir${reinit} : dossier de stockage des données (logs) de ${gras}${bleu}$scriptname${reinit}.

${bleu}${underline}NOTES${reinit}
	- Le $modeCC (${vert}-C${reinit}) va permettre de générer le fichier de configuration et de vérifier les dépendances du script.
	- Le fichier de configuration ${gras}${bleu}$(basename "$config")${reinit} conserve l'e-mail nécessaire à l'option ${vert}-m${reinit} ainsi que le mot de passe de ${gras}${bleu}$(whoami)${reinit}.
	- Il conserve aussi les options par défaut de ${gras}${bleu}$scriptname${reinit}.
	- Ce mot de passe, utilisé par la commande ${gras}${bleu}sudo${reinit}, peut-être stocké en clair, ou chiffré si la bibliothèque ${gras}${bleu}openssl${reinit} est installée.
	- Le $modeM (${vert}-m${reinit}) et le $modeN (${vert}-n${reinit}) ne sont appliqués qu'en $modeC (${vert}-c${reinit}). Ils sont ignorés sinon.
	- Le $modeM (${vert}-m${reinit}) nécessite la commande ${gras}${bleu}mail${reinit} et un MTA configuré (Mail Transport Agent, comme ${gras}${bleu}msmtp${reinit} ou ${gras}${bleu}opensmtpd${reinit}).
	- Une rotation des logs est effectuée dans ${gras}${bleu}$datadir${reinit} à chaque exécution de ${gras}${bleu}$scriptname${reinit}.
	- ${gras}9 logs${reinit} de chaque type sont conservés au maximum. Les logs vides sont automatiquement supprimés.
	- Le $modeV (${vert}-v${reinit}) permet d'outrepasser le $modeS (${vert}-s${reinit}) si ce dernier est activé par défaut dans ${gras}${bleu}$(basename "$config")${reinit},
	- Le $modeMM (${vert}-M${reinit}) permet d'outrepasser le $modeM (${vert}-m${reinit}) si ce dernier est activé par défaut dans ${gras}${bleu}$(basename "$config")${reinit}.
")" || true
	THE-END "succès" || true
	exit 0
}
################################################################################################################################
INSTALLED_DISTRO() {
    local dateepoch
    if EXISTS stat; then
        dateepoch="$(stat -c %W "/etc" 2>/dev/null)" || dateepoch=0
        days_since_install=$(( ( $(date +%s) - $(date +%s -d @"$dateepoch" 2>/dev/null) ) / 86400 )) || days_since_install="NA"
        datecreated=$(date -d @"$dateepoch" +"%e %B %Y" 2>/dev/null) || datecreated="inconnue"
        if [ "$days_since_install" -eq 1 ]; then
            day="jour"
        else
            day="jours"
        fi
    else
        datecreated="inconnue"
    fi
    return 0
}
################################################################################################################################
OFFLINE-UPGRADE() {
	local delay=5
	local largeur=15
	CECHO "[INFO]" "$vert" -n && echo -n " Téléchargement des paquets "
	DNF_OFF-UPDATECMD
	#if [ "$silent" = "yes" ]; then
	#	$bat "$list" || true
	#fi
	# Gestion des erreurs de téléchargement
	if [ -s "$logerror" ]; then
		if grep -iqE "$pattern_error" "$logerror"; then
			error="yes"
			echo
			CECHO "[WARN]" "$jaune" -n && echo " Le téléchargement a rencontré des erreurs (pas forcément grave, veuillez vérifier) : "
			echo "------------------------"
			$bat "$logerror" || true
			echo "------------------------"
			echo
			if ! ASK-YESNO "" "$vert" " Voulez-vous continuer (oui/non) ? " "$magenta" ""; then
				if ASK-YESNO " Redémarrage annulé par l'utilisateur... " "$vert" " Voulez-vous supprimer les paquets téléchargés non installés (oui/non) ? " "$magenta" "[INFO]"; then
					DNF_OFF-CLEANCMD || true
					CECHO "[INFO]" "$vert" -n && echo " Tous les paquets du cache de mise à jour hors-ligne ont été effacés."
				else
					CECHO "[INFO]" "$vert" -n && echo " Vous pouvez utiliser la commande suivante pour terminer manuellement la mise à jour :"
					echo -e "${bleu}	sudo dnf offline-upgrade -y reboot${reinit}"
					CECHO "[INFO]" "$vert" -n && echo " Vous pouvez utiliser la commande suivante pour supprimer manuellement les paquets téléchargés :"
					echo -e "${bleu}	sudo dnf offline-upgrade clean${reinit}"
				fi
				THE-END "des erreurs" || true
				exit 1
			fi
		fi
	fi
	if ASK-YESNO " Le script va maintenant redémarrer le système et faire la mise à jour hors-ligne." "$vert" " Êtes-vous d'accord (oui/non) ? " "$magenta" "[INFO]"; then
		echo
		CECHO "[INFO]" "$vert" -n && echo " L'ordinateur va redémarrer dans ${delay}s :"
		if [ "$poweroff" = "yes" ]; then
			COMPTEUR $delay $largeur "==> Redémarrage pour la mise à jour hors-ligne, puis arrêt de l'ordinateur <==" "$gras$jaune" || true
		else
			COMPTEUR $delay $largeur "==> Redémarrage pour la mise à jour hors-ligne, puis allumage de l'ordinateur <==" "$gras$jaune" || true
		fi
		if DNF_CHECK_OFFLINE_UPGRADE_READY; then
			THE-END "succès" || true
			echo "$dnf" > "$offlineindicator" || true  # Ce fichier sera détecté par un service systemd après reboot pour afficher un message
			sleep 2 || true
			#echo "DEBUG : check logs rotate" && read -r
			DNF_OFF-REBOOTCMD
		else
			echo
			CECHO "[ERR.]" "$rouge" -n && echo " Le redémarrage n'est pas possible."
			SUDOPASS
			# shellcheck disable=SC2024
			sudo $dnf offline-upgrade reboot >> "$logerror" 2>&1
			tail -n4 "$logerror"
			THE-END "des erreurs" || true
			exit 1
		fi
	else
		if ASK-YESNO " Redémarrage annulé par l'utilisateur... " "$vert" " Voulez-vous supprimer les paquets téléchargés non installés (oui/non) ? " "$magenta" "[INFO]"; then
			DNF_OFF-CLEANCMD || true
			CECHO "[INFO]" "$vert" -n && echo " Tous les paquets du cache de mise à jour hors-ligne ont été effacés."
		else
			CECHO "[INFO]" "$vert" -n && echo " Vous pouvez utiliser la commande suivante pour terminer manuellement la mise à jour :"
			echo -e "${bleu}	sudo dnf offline-upgrade -y reboot${reinit}"
			CECHO "[INFO]" "$vert" -n && echo " Vous pouvez utiliser la commande suivante pour supprimer manuellement les paquets téléchargés :"
			echo -e "${bleu}	sudo dnf offline-upgrade clean${reinit}"
		fi
	fi
	return 0
}
################################################################################################################################
ONLINE-UPGRADE() {
	local delay=5
	local largeur=15
	CECHO "[INFO]" "$vert" -n && echo -n " Téléchargement des paquets et mise à jour directe "
	DNF_UPDATECMD
	if [ "$silent" = "yes" ]; then
		$bat "$list" || true
	fi
	# Gestion des erreurs de téléchargement
	if [ -s "$logerror" ]; then
		if grep -iqE "$pattern_error" "$logerror"; then
			error="yes"
			echo
			CECHO "[WARN]" "$jaune" -n && echo " La mise à jour directe a rencontré des erreurs (pas forcément grave, veuillez vérifier) : "
			echo "------------------------"
			$bat "$logerror" || true
			echo "------------------------"
			echo
			if ! ASK-YESNO "" "$vert" " Voulez-vous continuer (oui/non) ? " "$magenta" ""; then
				THE-END "des erreurs" || true
				exit 1
			fi
		fi
	fi
	if [ "$poweroff" = "yes" ]; then
		CECHO "[INFO]" "$vert" -n && echo " L'ordinateur va s'éteindre dans ${delay}s (argument ${vert}-p${reinit}) :"
		COMPTEUR $delay $largeur "==> Extinction de l'ordinateur <==" "$gras$jaune" || true
		sleep 1 || true
		systemctl poweroff || true
	fi
	return 0
}
################################################################################################################################
SEND-EMAIL() {
	local type="$1" # RPM ou FP
	local liste="$2"
	export USERLOCAL="root"

	CECHO "[INFO]" "$vert" -n && echo -n " Envoi d'un email à $email "
	echo " => veuillez éxécuter la commande ${scriptfullname} sur $host pour procéder à la mise à jour." >> "$liste" || true
	{ trap STOP-SPINNER EXIT && START-SPINNER; }
		LANG="$LANG0" mail -s "[$host] Des mises à jour $type sont disponibles" "$email" < "$liste" || true
	{ STOP-SPINNER && echo "terminé."; }
	return 0
}
################################################################################################################################
GESTION-NOTIF() {
	local type
	type="$1"
	local liste
	liste="$2"
	local message
	local icon
	local messagelong
	local tmp
	tmp="$HOME/.cache/file.tmp"
	declare -i attempt=0
	declare -i max_attempts=9
	icon="/usr/share/swcatalog/icons/fedora/128x128/org.mageia.dnfdragora.png"
	message="Mises à jour disponibles"
	# Extract and format list for the notification
	awk '{print $1}' "$liste" | sort -u | sed -E 's/\.aarch64$//; s/\.noarch$//; s/^org\.//' > "$tmp" || true
	messagelong="$(tr '\n' ',' < "$tmp" | sed 's/,/,   /g' | sed 's/[[:space:]]*,[[:space:]]*$/ /')" || messagelong="(Liste indisponible)"
	rm -f "$tmp"
	unset "$tmp"
	# Wait for D-Bus notifications to be ready (max 9 attempts)
	while ! dbus-send --session --dest=org.freedesktop.notifications --type=method_call \
			/org/freedesktop/notifications org.freedesktop.notifications.GetCapabilities >/dev/null 2>&1; do
		attempt=$((attempt + 1))
		if [ $attempt -ge $max_attempts ]; then
			DATE-ET-HEURE >> "$bigerror"
			echo "Avertissement : D-Bus n'est toujours pas prêt après $attempt tentatives. Continuation du script." >> "$bigerror" || true
			break  # Exit the loop and continue the script
		fi
		sleep 5 || true
	done
	# Send notification
	notify-send -i "$icon" -u critical --app-name "$scriptname ($type)" "$message" "$messagelong" || true
	return 0
}
################################################################################################################################
DISTRO-UPGRADE() {
	echo
	PRINTBANNER-CENTERED "MISE À NIVEAU" "." "$cyan"
	local -i VERSION_PLUS
	local -i VERSION
	local delay=5
	local largeur=15
	VERSION=$VERSION_ID # from /etc/os-release
	VERSION_PLUS=$((VERSION_ID + 1))
	CECHO "[INFO]" "$vert" -n && echo -e " Montée en version de ${gras}${host}${reinit} de la version ${gras}${jaune}${VERSION}${reinit} vers la version ${gras}${jaune}${VERSION_PLUS}${reinit}."
	if ! ASK-YESNO " Validez-vous la version cible ($VERSION_PLUS) ? " "$magenta" " oui / non : " "$magenta" "[ACT.]"; then
		CECHO "[INFO]" "$vert" -n && echo -e "${gras} Montée en version annulée par l'utilisateur.${reinit}"
		return 0
	fi
	DNF_UPGRADECMD $VERSION_PLUS
	# Gestion des erreurs de téléchargement
	if [ -s "$logerror" ]; then
		echo
		CECHO "[WARN]" "$jaune" -n && echo " La montée en version a rencontré des erreurs (pas forcément grave, veuillez vérifier) : "
		echo "------------------------"
		$bat "$logerror" || true
		echo "------------------------"
		if ! ASK-YESNO "" "$vert" " Voulez-vous continuer (oui/non) ? " "$magenta" ""; then
			THE-END "des erreurs" || true
			exit 1
		fi
	fi
	if ASK-YESNO " Le script va maintenant redémarrer le système et faire la mise à jour hors-ligne." "$vert" " Êtes-vous d'accord (oui/non) ? " "$magenta" "[INFO]"; then
		echo
		CECHO "[INFO]" "$vert" -n && echo " L'ordinateur va redémarrer dans ${delay}s :"
		if [ "$poweroff" = "yes" ]; then
			COMPTEUR $delay $largeur "==> Redémarrage pour la mise à jour hors-ligne, puis arrêt de l'ordinateur <==" "$gras$jaune" || true
		else
			COMPTEUR $delay $largeur "==> Redémarrage pour la mise à jour hors-ligne, puis allumage de l'ordinateur <==" "$gras$jaune" || true
		fi
		if DNF_CHECK_OFFLINE_UPGRADE_READY; then
			THE-END "succès" || true
			sleep 2 || true
			DNF_UPGRADE-REBOOTCMD
		else
			echo
			CECHO "[ERR.]" "$rouge" -n && echo " Le redémarrage n'est pas possible."
			SUDOPASS
			# shellcheck disable=SC2024
			sudo $dnf offline-upgrade reboot >> "$logerror" 2>&1
			THE-END "des erreurs" || true
			exit 1
		fi
	else
		if ASK-YESNO " Redémarrage annulé par l'utilisateur... " "$vert" " Voulez-vous supprimer les paquets téléchargés non installés (oui/non) ? " "$magenta" "[INFO]"; then
			DNF_UPGRADE-CLEANCMD || true
			CECHO "[INFO]" "$vert" -n && echo " Tous les paquets du cache de mise à jour hors-ligne ont été effacés."
		else
			CECHO "[INFO]" "$vert" -n && echo " Vous pouvez utiliser la commande suivante pour terminer manuellement la mise à jour :"
			echo -e "${bleu}	sudo dnf offline-upgrade -y reboot${reinit}"
			CECHO "[INFO]" "$vert" -n && echo " Vous pouvez utiliser la commande suivante pour supprimer manuellement les paquets téléchargés :"
			echo -e "${bleu}	sudo dnf offline-upgrade clean${reinit}"
		fi
	fi
	return 0
}
################################################################################################################################
CHECKRPM() {
	listtmp="$HOME/.cache/list.tmp"
	if [ -z "$nocacheupd" ]; then
		CECHO "[INFO]" "$vert" -n && echo -n " Mise à jour forcée du cache des métadonnées "
		DNF_CLEANCMD
		DNF_CACHEUPDCMD
	fi
	CECHO "[INFO]" "$vert" -n && echo -n " Vérification des paquets disponibles "
	DNF_CHECKUPDCMD
	# Format and filter list of updates
	if [ "$silent" = "yes" ] && [ "$changelog" = "yes" ]; then
		$bat "$listtmp"
	fi
	awk '/^Changelogs/ {exit} {if (NF > 0) printf "  %-45s %-7s\n", $1, $2}' "$listtmp" > "$list" || true
	rm -f "$listtmp"
	unset listtmp
	# Check for errors and output results
	if [ -s "$logerror" ]; then
		if grep -iqE "$pattern_error" "$logerror"; then
			error="yes"
			CECHO "[ERR.]" "$rouge" -n && echo " La vérification a rencontré des erreurs :"
			echo "------------------------"
			$bat "$logerror" || true
			echo "------------------------"
			echo
			if ! ASK-YESNO "" "$vert" " Voulez-vous continuer (oui/non) ? " "$magenta" ""; then
				THE-END "des erreurs" || true
				exit 1
			fi
		fi
	fi
	if [ -s "$list" ]; then
		existupdateRPM="yes"
		return 0
	else
		return 1
	fi
}
################################################################################################################################
GESTION-RPM() {
	echo
	PRINTBANNER-CENTERED "GESTION DES RPMs" "." "$cyan"
	if CHECKRPM; then
		if [ "$silent" = "yes" ] && [ "$changelog" = "" ] ; then
			$bat "$list" || true
		fi
		if [ -z "$checkonly" ]; then 	# mode normal
			if [ "$directrpms" = "yes" ]; then
				ONLINE-UPGRADE || true
			else
				if [ "$distrupgrade" = "yes" ]; then
			 		CECHO "[INFO]" "$vert" -n && echo -e " Le $modeU est ignoré pour le moment car des mises à jour sont à faire avant."
					CECHO "[INFO]" "$vert" -n && echo -e " Après la mise à jour vous pourrez relancer ${gras}$scriptfullname -u${reinit}."
					distrupgrade=""
				fi
				OFFLINE-UPGRADE || true
			fi
		else  							# mode checkonly
			CECHO "[INFO]" "$vert" -n && echo " Des mises à jour sont disponibles."
			if [ "$distrupgrade" = "yes" ]; then
		 		CECHO "[INFO]" "$vert" -n && echo -e " Le $modeU est ignoré pour le moment car des mises à jour sont à faire avant."
				CECHO "[INFO]" "$vert" -n && echo -e " Après la mise à jour vous pourrez relancer ${gras}$scriptfullname -u${reinit}."
				distrupgrade=""
			fi
			[ "$notif" = "yes" ] && { GESTION-NOTIF "RPM" "$list" || true ;}
			[ "$notif_email" = "yes" ] && { SEND-EMAIL "RPM" "$list" || true ;}
		fi
	else
		CECHO "[INFO]" "$vert" -n && echo -e " ${gras}Votre système ($host) est déjà à jour.${reinit}"
	fi
	return 0
}
################################################################################################################################
GESTION-Flatpak() {
	listtmpFP="$HOME/.cache/listFP.tmp"
	if EXISTS flatpak; then
		flatpak="$(which flatpak 2>/dev/null)"
		INIT-LOGFP || true
		echo
		PRINTBANNER-CENTERED "GESTION DES FLATPAKs" "." "$cyan"
		# Check for available updates
		CECHO "[INFO]" "$vert" -n && echo -n " Vérification des paquets disponibles "
		FPK_CHECKUPDCMD
		#cat "$listtmpFP" | awk '{printf "%-45s %-7s\n", $2, $3}' | sed 's/^/  /' > "$listFP" || true
		#awk '{printf "%-45s %-7s\n", $2, $3}' "$listtmpFP" | sed 's/^/  /' > "$listFP" || true
		awk '{printf "  %-45s %-7s\n", $2, $3}' "$listtmpFP" > "$listFP" || true
		rm -f "$listtmpFP"
		unset listtmpFP
		# Check for verification errors
		if [ -s "$logerrorFP" ]; then
			CECHO "[ERR.]" "$rouge" -n && echo " La vérification a rencontré des erreurs :"
			echo "------------------------"
			$bat "$logerrorFP" || true
			echo "------------------------"
			echo
		else
			if [ -s "$listFP" ]; then # fichier non vide donc il y a des maj
				existupdateFP="yes"
				# Display logs based on `silent` mode
				if [ -n "$silent" ]; then
					$bat "$listFP" || true
				fi
				if [ -z "$checkonly" ]; then
					# Download and install updates
					CECHO "[INFO]" "$vert" -n && echo -n " Mise à jour des paquets "
					FPK_UPDCMD
					# Check for errors during the update process
					if [ -s "$logerrorFP" ]; then
						CECHO "[ERR.]" "$rouge" -n && echo " Le téléchargement a rencontré des erreurs : "
						echo "------------------------"
						$bat "$logerrorFP" || true
						echo "------------------------"
						echo
					fi
				else  # Mode checkonly
					CECHO "[INFO]" "$vert" -n && echo " Des mises à jour sont disponibles."
					[ "$notif" = "yes" ] && { GESTION-NOTIF "FLATPAK" "$listFP" || true ;}
					[ "$notif_email" = "yes" ] && { SEND-EMAIL "FLATPAK" "$listFP" || true ;}
				fi
			else
				CECHO "[INFO]" "$vert" -n && echo -e " ${gras}Votre système ($host) est déjà à jour.${reinit}"
			fi
		fi
	else
		echo
		CECHO "[INFO]" "$vert" -n && echo -e " La commande ${gras}${bleu}flatpak${reinit} n'est pas détectée sur ce système."
		CECHO "[INFO]" "$vert" -n && echo -e " Vous pouvez l'installer avec la commande : ${gras}${bleu}sudo dnf install flatpak${reinit}."
		CECHO "[INFO]" "$vert" -n && echo " En attendant, la gestion des FLATPAKs est désactivée."
	fi
	return 0
}
################################################################################################################################
GESTION-OPTIONS() { # management des options du script sélectionnées via la ligne de commande ou le fichier de conf
	if [ "$datecreated" != "inconnue" ]; then
		CECHO "[INFO]" "$vert" -n
		echo -e " Date d'installation de ${ID^} (${gras}$host${reinit}) :${italic}$datecreated${reinit} (il y a ${days_since_install} $day)" || true
	fi
	CECHO "[INFO]" "$vert" -n && echo -e " Ligne de commande : ${gras}${bleu}${scriptfullname}${reinit} ${gras}${vert}${cmdline}${reinit}" | tee -a "$biglog"

# Affichage des modes selectionnés
	[ "$checkdeps" = "yes" ] && echo -e " $modeCC (${vert}-C${reinit})." >> "$biglog"
	[ "$silent" = "yes" ] && echo -e " $modeS (${vert}-s${reinit})." >> "$biglog"
	[ "$verbose" = "yes" ] && echo -e " $modeV (${vert}-v${reinit})." >> "$biglog"
	[ "$nomail" = "yes" ] && echo -e " $modeMM (${vert}-M${reinit})." >> "$biglog"
	[ "$noflatpak" = "yes" ] && echo -e " $modeF (${vert}-F${reinit})." >> "$biglog"
	[ "$norpm" = "yes" ] && echo -e " $modeR (${vert}-R${reinit})." >> "$biglog"
	[ "$nolog" = "yes" ] && echo -e " $mode0 (${vert}-0${reinit})." >> "$biglog"
	[ "$limitlog" = "yes" ] && echo -e " $modeLP (${vert}-l${reinit})." >> "$biglog"
	[ "$directrpms" = "yes" ] && echo -e " $modeD (${vert}-d${reinit})." >> "$biglog"
	[ "$nocacheupd" = "yes" ] && echo -e " $modeB (${vert}-B${reinit})." >> "$biglog"
	[ "$forcecacheupd" = "yes" ] && echo -e " $modeBB (${vert}-b${reinit})." >> "$biglog"
	[ "$poweroff" = "yes" ] && echo -e " $modeP (${vert}-p${reinit})." >> "$biglog"
	[ "$changelog" = "yes" ] && echo -e " $modeCL (${vert}-L${reinit})." >> "$biglog"
	[ "$distrupgrade" = "yes" ] && echo -e " $modeU (${vert}-u${reinit})." >> "$biglog"
	[ "$checkonly" = "yes" ] && echo -e " $modeC (${vert}-c${reinit})." >> "$biglog"
	[ "$deletelog" = "yes" ] && echo -e " ${jaune}mode \"suppression des logs\"${reinit} (${vert}-D${reinit})." >> "$biglog"
	[ "$forcednf4" = "yes" ] && { echo -e " $mode4 (${vert}-4${reinit})." >> "$biglog" ; dnf="/usr/bin/dnf4" ;}
	[ "$forcednf5" = "yes" ] && { echo -e " $mode5 (${vert}-5${reinit})." >> "$biglog" ; dnf="/usr/bin/dnf5" ;}
#----------------------------------

# Gestion des incompatibilités de modes
	if [ "$silent" = "yes" ] && [ "$verbose" = "yes" ]; then
		echo -e " Le $modeS (${vert}-s${reinit}) est incompatible avec le $modeV (${vert}-v${reinit})." >> "$biglog"
		echo -e " On force donc le $modeV (${vert}-v${reinit})." >> "$biglog"
		silent=""
	fi
	if [ "$silent" = "yes" ] && [ "$distrupgrade" = "yes" ]; then
		echo -e " En $modeU (${vert}-u${reinit}), on désactive le $modeS (${vert}-s${reinit})." >> "$biglog"
		silent=""
	fi
	if [ "$forcednf4" = "yes" ] && [ "$forcednf5" = "yes" ]; then
		echo -e " Les modes ${gras}${bleu}dnf4${reinit} et ${gras}${bleu}dnf5${reinit} ne peuvent être utilisés en même temps." >> "$biglog"
		echo -e " On utilise ${gras}${bleu}/usr/bin/dnf${reinit}." >> "$biglog"
		dnf="/usr/bin/dnf"
		forcednf4=""
		forcednf5=""
	fi
	if { [ "$forcednf4" = "yes" ] || [ "$forcednf5" = "yes" ]; } && [ "$distrupgrade" = "yes" ]; then
		echo -e " Les modes forcés ${gras}${bleu}dnf4${reinit} et ${gras}${bleu}dnf5${reinit} ne sont pas compatibles avec le $modeU (${vert}-u${reinit})." >> "$biglog"
		echo -e " On utilise ${gras}${bleu}/usr/bin/dnf${reinit}." >> "$biglog"
		dnf="/usr/bin/dnf"
		forcednf4=""
		forcednf5=""
	fi
	if [ "$distrupgrade" = "yes" ] && [ "$nocacheupd" = "yes" ]; then
		echo -e " Le $modeU (${vert}-u${reinit}) est incompatible avec le $modeB (${vert}-B${reinit})." >> "$biglog"
		echo -e " On ignore donc le $modeB (${vert}-B${reinit})." >> "$biglog"
		nocacheupd=""
	fi
	if [ "$distrupgrade" = "yes" ] && [ "$norpm" = "yes" ]; then
		echo -e " Le $modeU (${vert}-u${reinit}) est incompatible avec le $modeR (${vert}-R${reinit})." >> "$biglog"
		echo -e " On ignore donc le $modeR (${vert}-R${reinit})." >> "$biglog"
		norpm=""
	fi
	if [ "$nocacheupd" = "yes" ] && [ "$forcecacheupd" = "yes" ]; then
		echo -e " Le $modeB (${vert}-B${reinit}) est incompatible avec le $modeBB (${vert}-b${reinit})." >> "$biglog"
		echo -e " On force donc le $modeBB (${vert}-b${reinit})." >> "$biglog"
		nocacheupd=""
	fi
#----------------------------------

# Contrôles du mode email (verif adresse email existe et commande mail est installée)
	if [ "$notif_email" = "yes" ]; then
		if [ -z "$email" ]; then
			DATE-ET-HEURE >> "$bigerror" || true
			CECHO "[WARN]" "$jaune" -n && { echo " Aucune adresse email trouvée." | tee -a "$bigerror" || true ;}
			CECHO "[INFO]" "$vert" -n && { echo " Veuillez exécuter la commande suivante pour créer le fichier de configuration :" | tee -a "$bigerror" || true ;}
			echo -e "	${gras}${bleu}$scriptfullname -C${reinit}" | tee -a "$bigerror" || true
			THE-END "des erreurs" | tee -a "$bigerror" || true
			exit 1
		else
			echo -e " e-mail : ${bleu}$email${reinit}." >> "$biglog"
		fi
		if ! EXISTS mail; then
			DATE-ET-HEURE >> "$bigerror" || true
			CECHO "[ERR.]" "$rouge" -n && { echo -e " La commande ${gras}${bleu}mail${reinit} n'est pas disponible sur votre système." | tee -a "$bigerror" || true ;}
			CECHO "[INFO]" "$vert" -n && { echo -e " Vous pouvez l'installer avec la commande : ${gras}${bleu}sudo dnf install s-nail${reinit}." | tee -a "$bigerror" || true ;}
			CECHO "[WARN]" "$jaune" -n && { echo -e " Vous devez aussi installer et configurer un \"Mail Transport Agent\", par exemple ${gras}${bleu}msmtp${reinit} avec la commande ${gras}${bleu}sudo dnf install msmtp${reinit}." | tee -a "$bigerror" || true ;}
		fi
	fi
#----------------------------------

# Contrôle du mode vérification (incompatibilités avec et sans le mode -c)
	if [ "$checkonly" = "yes" ]; then
		if [ "$distrupgrade" = "yes" ]; then
			echo -e " Le $modeU (${vert}-u${reinit}) est incompatible avec le $modeC (${vert}-c${reinit})." >> "$biglog"
			echo -e " On ignore donc le $modeU (${vert}-u${reinit})." >> "$biglog"
			distrupgrade=""
		fi
		if [ "$notif_email" = "yes" ]; then
			echo -e " $modeM (${vert}-m${reinit})." >> "$biglog"
			if [ "$nomail" = "yes" ]; then
				echo -e " Le $modeM (${vert}-m${reinit}) est incompatible avec le $modeMM (${vert}-M${reinit})." >> "$biglog"
				echo -e " On ignore donc le $modeM (${vert}-m${reinit})." >> "$biglog"
				notif_email=""
			fi
		fi
		if [ "$notif" = "yes" ]; then
			echo -e " $modeN (${vert}-n${reinit})." >> "$biglog"
		fi
	else
		if [ "$notif_email" = "yes" ]; then
			echo -e " $modeM (${vert}-m${reinit}) ignoré car le $modeC (${vert}-c${reinit}) n'est pas activé." >> "$biglog"
			notif_email=""
		fi
		if [ "$notif" = "yes" ]; then
			echo -e " $modeN (${vert}-n${reinit}) ignoré car le $modeC (${vert}-c${reinit}) n'est pas activé." >> "$biglog"
			notif=""
		fi
	fi
#----------------------------------

# Finalisation
	CECHO "[INFO]" "$vert" -n && echo -en " Options retenues (arguments longs) : ${gras}${vert}" | tee -a "$biglog"
	for opts in silent verbose help checkonly notif_email nomail notif noflatpak norpm nolog checkdeps directrpms nocacheupd \
				forcecacheupd poweroff changelog forcednf4 forcednf5 distrupgrade limitlog deletelog ; do
	    if [ "${!opts}" = "yes" ]; then
       	echo -n "--$opts " | tee -a "$biglog"
       fi
   done
	echo -e "${reinit}" | tee -a "$biglog"
	dnfver="$(CHECK_DNF_VERSION || echo "unknown")"
	[ "$norpm" = "" ] && INIT-LOGRPM
#----------------------------------

return 0
}
################################################################################################################################
LOG-ROTATE() {
    declare -i max_logs=10
    local -A log_prefixes=(
        [log]="$log"
        [logFP]="$logFP"
        [logerror]="$logerror"
        [logerrorFP]="$logerrorFP"
        [bigerror]="$bigerror"
        [biglog]="$biglog"
    )
    for key in "${!log_prefixes[@]}"; do
        local prefix="${log_prefixes[$key]}"
        # Supprime le fichier de log le plus ancien s'il existe (par exemple, .log.(max_logs-1))
        local oldest_log="$datadir/${prefix}.log.$((max_logs - 1))"
        if [[ -e "$oldest_log" ]]; then
            rm -f "$oldest_log" || { echo "Échec lors de la suppression de $oldest_log" >&2; return 1; }
        fi
        # Décale les fichiers de log existants d'un suffixe, en commençant par le suffixe le plus élevé jusqu'à .log.1
        for (( i=max_logs-2; i>=1; i-- )); do
            local old_log="$datadir/${prefix}.log.$i"
            local new_log="$datadir/${prefix}.log.$((i + 1))"
            if [[ -e "$old_log" ]]; then
                mv "$old_log" "$new_log" || { echo "Échec lors du renommage de $old_log en $new_log" >&2; return 1; }
            fi
        done
        # Renomme le fichier .log actuel en .log.1 s'il existe
        if [[ -e "$datadir/${prefix}.log" ]]; then
            mv "$datadir/${prefix}.log" "$datadir/${prefix}.log.1" || { echo "Échec lors du renommage de ${prefix}.log en ${prefix}.log.1" >&2; return 1; }
        fi
        # Met à jour la variable globale pour qu'elle pointe vers le fichier de log actuel, qui est toujours .log
        eval "$key=\"$datadir/${prefix}.log\""
    done
}
################################################################################################################################
INIT-LOGFP() {
	{	DATE-ET-HEURE ;
		echo "$scriptfullname $cmdline (v$ver)" ;
		echo ;
		echo "----------------------" ;
		echo "flatpak version :" ;
	} >> "$logFP"
	if ! $flatpak --version >> "$logFP"; then
	    echo "Echec flatpak --version." | tee -a "$logFP"
	fi
	{ echo "----------------------" ; echo ; } >> "$logFP"
}
################################################################################################################################
INIT-LOGRPM() {
	{ 	DATE-ET-HEURE ;
		echo "$scriptfullname $cmdline (v$ver)" ;
		echo ;
		echo "----------------------" ;
		echo "dnf $dnf, $dnfver, version :" ;
	} >> "$log"
	if ! $dnf --version >> "$log"; then
	    echo "Echec $dnf --version. Est-ce que dnf est installé ?" | tee -a "$log"
	fi
	{ echo "----------------------" ; echo ; } >> "$log"
}
################################################################################################################################
FINAL-LOGS() {
	islogrotate=""
	local existupdate=""
	if [ "$existupdateRPM" = "yes" ] || [ "$existupdateFP" = "yes" ]; then # pour définir s'il y a eu des maj
		existupdate="yes"
	fi
	if [ "$limitlog" = "yes" ] && [ "$existupdate" = "yes" ] ; then # on tourne les log en cas de mode limitlog ON avec des maj, si le mode nolog est OFF
		[ "$nolog" = "" ] && islogrotate="yes"
	fi
	if [ "$limitlog" = "yes" ] && [ "$existupdate" = "" ] ; then # on force la suppression des logs en mode limitlog ON sans maj.
		nolog="yes" # forçage suppression du fichier
	fi
	if [ "$limitlog" = "" ] ; then # si les modes limitlog et nolog ne sont pas activés, on tourne les logs
		[ "$nolog" = "" ] && islogrotate="yes"
	fi
	for fiche in "$logerrorFPtmp" "$logerrortmp" "$logtmp" "$logFPtmp" "$bigerrortmp" "$biglogtmp"; do
		if [ "$nolog" = "yes" ]; then
			rm -f "$fiche"
		else
			if [ ! -s "$fiche" ]; then # suppression si vide
				rm -f "$fiche"
			fi
		fi
	done
    [ "$errorargs" = "yes" ] && islogrotate=""
	if [ "$islogrotate" = "yes" ] ; then
		log="${scriptname}-RPM"
		logFP="${scriptname}-Flatpak"
		logerrorFP="${scriptname}-Flatpak.error"
		logerror="${scriptname}-RPM.error"
		bigerror="${scriptname}.error"
		biglog="${scriptname}"
		LOG-ROTATE || true
		rm -f "$log" "$logFP" "$logerror" "$logerrorFP" "$bigerror" "$list" "$listFP" "$biglog"
		touch "$log" "$logFP" "$logerror" "$logerrorFP" "$bigerror" "$list" "$listFP" "$biglog" || { echo "Echec lors de la création des logs" >&2; exit 1; }
		chmod 640 "$log" "$logFP" "$logerror" "$logerrorFP" "$bigerror" "$list" "$listFP" "$biglog" || { echo "Echec lors de la création des droits" >&2; exit 1; }
	fi
}
################################################################################################################################
INIT-TEMPLOGS() {
	datadir="$HOME/.local/share/${scriptname}"
	confdir="$HOME/.config/${scriptname}"
	passwordencrypted="$datadir/.password.enc"
	privatekey="$datadir/.${scriptname}_rsa.pem"
	config="$confdir/config.rc"
	# Ensure data and config directories exist
	[ ! -d "$datadir" ] && { mkdir -p "$datadir" || true ;}
	[ ! -d "$confdir" ] && { mkdir -p "$confdir" || true ;}
	log="$HOME/.cache/${scriptname}-RPM.log"
	logFP="$HOME/.cache/${scriptname}-Flatpak.log"
	logerrorFP="$HOME/.cache/${scriptname}-Flatpak.error.log"
	logerror="$HOME/.cache/${scriptname}-RPM.error.log"
	bigerror="$HOME/.cache/${scriptname}.error.log"
	biglog="$HOME/.cache/${scriptname}.log"
	list="$HOME/.cache/RPMs.tmp.list"
	listFP="$HOME/.cache/Flatpaks.tmp.list"
	logerrorFPtmp="$logerrorFP"
	logerrortmp="$logerror"
	logtmp="$log"
	logFPtmp="$logFP"
	bigerrortmp="$bigerror"
	biglogtmp="$biglog"
	rm -f "$log" "$logFP" "$logerror" "$logerrorFP" "$bigerror" "$list" "$listFP" "$biglog"
	touch "$log" "$logFP" "$logerror" "$logerrorFP" "$bigerror" "$list" "$listFP" "$biglog" || { echo "Echec lors de la création des logs" >&2; exit 1; }
	chmod 640 "$log" "$logFP" "$logerror" "$logerrorFP" "$bigerror" "$list" "$listFP" "$biglog" || { echo "Echec lors de la création des droits" >&2; exit 1; }
}
################################################################################################################################
VIEWER() {
	if EXISTS bat; then
			if bat --list-themes | grep -q zenburn ; then
				bat="bat -P -f -n -l log --theme=zenburn"
			else
				bat="bat -P -f -n -l log"
			fi
	else
			bat="cat"
	fi
}
################################################################################################################################
START() {
	UNALIAS || true

# Initialisation des variables globales
	LANG0="$LANG" # backup initial LANG set.
	export LANG=C # force simple-english outputs
	dnf="/usr/bin/dnf"
	declare -gi days_since_install=0
	declare -gi spinner_pid=1	# variable qui va contenir le PID pour tuer le spinner (cf START/STOP-SPINNER).
	day=""
	terminal="$TERM"
	INITCOLOR || true
	datecreated=""
	existupdateRPM=""
	existupdateFP=""
	help=""
	silent=""
	nolog=""
	checkonly=""
	notif=""
	notif_email=""
	noflatpak=""
	norpm=""
	checkdeps=""
	directrpms=""
	nocacheupd=""
	forcecacheupd=""
	email=""
	password=""
	poweroff=""
	changelog=""
	forcednf4=""
	forcednf5=""
	distrupgrade=""
	limitlog=""
	dnfver=""
	verbose=""
	nomail=""
	errorargs=""
	error=""
	deletelog=""
	pattern_error="'error|erreur|cannot install|warning|There is already an offline transaction queued'"
	modeS="${jaune}mode \"pseudo-silencieux\"${reinit}"
	modeV="${jaune}mode \"verbeux\"${reinit}"
	modeC="${jaune}mode \"vérification\"${reinit}"
	modeM="${jaune}mode \"notification par email\"${reinit}"
	modeMM="${jaune}mode \"pas de notification par email\"${reinit}"
	modeN="${jaune}mode \"notification système\"${reinit}"
	modeF="${jaune}mode \"sans gestion des FLATPAKs\"${reinit}"
	modeR="${jaune}mode \"sans gestion des RPMs\"${reinit}"
	mode0="${jaune}mode \"zéro log\"${reinit}"
	modeD="${jaune}mode \"mise à jour directe\"${reinit}"
	modeCC="${jaune}mode \"contrôle de fonctionnement\"${reinit}"
	modeB="${jaune}mode \"pas de mise à jour du cache\"${reinit}"
	modeBB="${jaune}mode \"mise à jour forcée du cache\"${reinit}"
	modeP="${jaune}mode \"extinction\"${reinit}"
	modeCL="${jaune}mode \"ChangeLog\"${reinit}"
	mode4="${jaune}mode \"dnf4\"${reinit}"
	mode5="${jaune}mode \"dnf5\"${reinit}"
	modeU="${jaune}mode \"mise à niveau\"${reinit}"
	modeLP="${jaune}mode \"logs partiels\"${reinit}"
	offlineindicator="$HOME/.offline-upgrade"

# Initialisation des logs et du viewer
	INIT-TEMPLOGS || true
	VIEWER || true

# Affichage initial
	if [ "$terminal" = "dumb" ]; then
		sleep 10 || true
	else
		CLEAR || true
	fi
	# shellcheck source=/dev/null
	source "/etc/os-release" || true
	rm -f "$datadir/.term"
	INSTALLED_DISTRO || true
	HOSTNAME || true
	PRINTBANNER-CENTERED " MISE À JOUR de $NAME $VERSION " "*" "$gras$bleu"
	CECHO "[INFO]" "$vert" -n && echo " Script démarré à $(DATE-ET-HEURE)." | tee -a "$biglog"
	CECHO "[INFO]" "$vert" -n && echo -e " Version du script : ${gras}${vert}$ver${reinit}" | tee -a "$biglog"

# controle des dependances
	CHECK || true
	return 0
}
################################################################################################################################
CLEAR-LOGS() {
	local fiche
	nblog=0
	listlog=""
	rm -f "$list" "$listFP"
	if [ "$limitlog" = "yes" ]; then
		[ "$existupdateFP" = ""  ] && rm -f "$logFP"
		[ "$existupdateRPM" = "" ] && rm -f "$log"
	fi
	for fiche in "$logerrorFP" "$logerror" "$log" "$logFP" "$bigerror" "$biglog"; do
		if [ "$nolog" = "yes" ]; then
			rm -f "$fiche"
		else
			if [ ! -s "$fiche" ]; then # suppression si vide
				rm -f "$fiche"
			else
				# on compte le nb de log, on ajoute la date ; et on les concatène pour afficher
				if [ "$fiche" = "$logerror" ] && [ "$error" = "yes" ]; then
					nblog=$(( nblog + 1 ))
					echo >> "$fiche"
					DATE-ET-HEURE >> "$fiche"
					listlog="${listlog}${fiche} "
				elif [ "$fiche" != "$logerror" ]; then
					nblog=$(( nblog + 1 ))
					echo >> "$fiche"
					DATE-ET-HEURE >> "$fiche"
					listlog="${listlog}${fiche} "
				fi
			fi
		fi
	done
}
################################################################################################################################
THE-END() {
	echo
	FINAL-LOGS || true
	for fiche in "$logerrorFPtmp" "$logerrortmp" "$logtmp" "$logFPtmp" "$bigerrortmp" "$biglogtmp"; do
		if [ -e "$fiche" ]; then
			mv -f "$fiche" "$datadir"
		fi
	done
	CLEAR-LOGS
	# Display available logs
	PRINTBANNER-CENTERED "" "." "$cyan"
	if [ "$islogrotate" = "yes" ]; then
		CECHO "[INFO]" "$vert" -n && echo " Rotation des logs."
	fi
	case $nblog in
		0) echo -n ;;
		1) CECHO "[INFO]" "$vert" -n ; echo " Log : $listlog" || true ;;
		*) CECHO "[INFO]" "$vert" -n ; echo " Logs : $listlog" || true ;;
	esac
	# Final message
	CECHO "[INFO]" "$vert" -n && echo -e " Script terminé avec $1 à $(DATE-ET-HEURE)."
	PRINTBANNER-CENTERED "" "*" "$gras$bleu"
	export LANG="$LANG0"
	return 0
}
################################################################################################################################
ERROR-ARGS() {
	CECHO "[ERR.]" "$rouge" -n && echo -e " Argument(s) inconnu(s) : ${rouge}$cmdline${reinit}"
	USAGE || true
	errorargs="yes"
	THE-END "des erreurs" || true
	exit 1
}
################################################################################################################################
LOAD-CONFIGRC() {
# On charge le fichier de configuration ou on s arrete s'il n'existe pas (si le script est lancé en auto, sinon on continue)
	if [ -f "$config" ]; then
		# shellcheck source=/dev/null
		source "$config" || true
	else
		if [ "$terminal" = "dumb" ]; then
			DATE-ET-HEURE >> "$bigerror" || true
			CECHO "[WARN]" "$jaune" -n && { echo " Fichier de conf introuvable" | tee -a "$bigerror" || true ;}
			CECHO "[INFO]" "$vert" -n && { echo " Veuillez exécuter la commande suivante pour créer le fichier de configuration :" | tee -a "$bigerror" || true ;}
			echo -e "	${gras}${bleu}$scriptfullname -C${reinit}" | tee -a "$bigerror" || true
			THE-END "des erreurs" | tee -a "$bigerror" || true
			exit 1
		fi
	fi
return 0
}
################################################################################################################################
DELETE-LOG() {
	CECHO "[INFO]" "$vert" -n && echo " Suppression de tous les logs."
	rm -f "$datadir"/*.log*
}
################################################################################################################################
GESTION-ARGS() {
	local options
	local arg
	# gestion de la ligne de commande avec arguments courts ou longs
	options=$(getopt -o 'svhcmMnFR0CdBbpL45ulD' \
	-l 'silent,verbose,help,checkonly,notif_mail,nomail,notify,noflatpak,norpm,nolog,checkdeps,directrpms,nocacheupd,forcecacheupd,poweroff, \
	changelog,forcednf4,forcednf5,distrupgrade,limitlog,deletelog' -- "$@" 2>/dev/null) || ERROR-ARGS
	eval set -- "$options"
	while true; do
		case "$1" in
			-s|--silent)        silent="yes"				; shift ;;
			-v|--verbose)       verbose="yes"				; shift ;;
			-h|--help)          help="yes"					; shift ;;
			-c|--checkonly)	    checkonly="yes"				; shift ;;
			-m|--notif_mail)    notif_email="yes"			; shift ;;
			-M|--nomail)        nomail="yes"				; shift ;;
			-n|--notify)        notif="yes"					; shift ;;
			-F|--noflatpak)     noflatpak="yes"				; shift ;;
			-R|--norpm)         norpm="yes"					; shift ;;
			-0|--nolog)         nolog="yes"					; shift ;;
			-C|--checkdeps)     checkdeps="yes"				; shift ;;
			-d|--directrpms)    directrpms="yes"			; shift ;;
			-B|--nocacheupd)    nocacheupd="yes"			; shift ;;
			-b|--forcecacheupd) forcecacheupd="yes"			; shift ;;
			-p|--poweroff)      poweroff="yes"				; shift ;;
			-L|--changelog)		changelog="yes"				; shift ;;
			-4|--forcednf4)		USE-DNF4					; shift ;;
			-5|--forcednf5)		USE-DNF5					; shift ;;
			-u|--distrupgrade)	distrupgrade="yes"			; shift ;;
			-l|--limitlog)		limitlog="yes"				; shift ;;
			-D|--deletelog)		deletelog="yes"				; shift ;;
			--)                 shift						; break ;; # End of options
			*)                  ERROR-ARGS							;;
		esac
	done
	for arg in "$@"; do
		if [[ "$arg" != -* ]]; then
			ERROR-ARGS
		fi
	done
	# /fin de gestion de la ligne de commande.
	return 0
}
################################################################################################################################

#################################################################################################################################
#                   CORPS DU SCRIPT                                                                                             #
#################################################################################################################################
START || true													 	 # initialisation du script 								#
GESTION-ARGS "$@"													 # gestion des arguments de la ligne de commande			#
LOAD-CONFIGRC														 # gestion des arguments du fichier config.rc				#
GESTION-OPTIONS || true										 		 # gestion des options (incompatibilités, vérif)			#
[ "$deletelog" = "yes" ]    && 	 DELETE-LOG					 		 # mode -D													#
[ "$help" = "yes" ]         && 	 DISPLAY-HELP                		 # mode -h (autonome)										#
[ "$checkdeps" = "yes" ]    &&   CHECK 	         			 		 # mode -C (autonome)										#
[ -z "$noflatpak" ]		    && { GESTION-Flatpak || true ; } 		 # Flatpak													#
[ -z "$norpm" ]				&& { GESTION-RPM     || true ; } 		 # RPM														#
[ "$distrupgrade" = "yes" ] && { DISTRO-UPGRADE  || true ; } 		 # mode -u													#
THE-END "succès" || true									 		 # finalisation du script (gestion des logs, ...)			#
exit 0																 # sortie propre											#
#################################################################################################################################
