.TH \fBfedupdate\fR 1 "22 Décembre 2024" "v1.7" "Documentation utilisateur"
.SH NAME
\fBfedupdate\fR \- Cette commande met à jour un système FEDORA Linux.
.SH SYNOPSIS
.B fedupdate
[-h] [-C] [-s] [-v] [-c] [-m] [-M] [-n] [-F] [-R] [-d] [-B] [-0] [-p] [-L] [-l] [-4] [-5] [-u] (ou arguments longs)

.SH DESCRIPTION
Si des nouveaux paquets \fBFLATPAKs\fR sont disponibles, une mise à jour est lancée.

Si des nouveaux paquets \fBRPMs\fR sont disponibles, la commande va les télécharger puis redémarrer le système pour faire une mise à jour hors-ligne.

Les erreurs de vérifications et de téléchargements sont gérées.

La commande doit être lancée par un utilisateur normal disposant du droit d'élévation de privilèges (via \fBsudo\fR).

.SH OPTIONS
.TP
.B \-h,--help
Affiche l'aide.
.TP
.B \-C,--checkdeps
Affiche et/ou crée le fichier de configuration, puis contrôle les dépendances.
.TP
.B \-s,--silent
Seules les erreurs et la liste de paquets seront affichées.
.TP
.B \-v,--verbose
Toutes les infos sont affichées (mode "verbeux").
.TP
.B \-c,--check
Pour vérifier si des mises à jour sont disponibles sans les installer.
.TP
.B \-m,--mail
Envoie un email si des mises à jour sont disponibles.
.TP
.B \-M,--nomail
Annule l'option -m (utile si l'option -m est activée par défaut dans config.rc).
.TP
.B \-n,--notify
Envoie une notification système si des mises à jour sont disponibles.
.TP
.B \-F,--noflatpak
Pour ignorer la gestion des FLATPAKs.
.TP
.B \-R,--norpm
Pour ignorer la gestion des RPMs.
.TP
.B \-d,--direct
Pour faire une mise à jour directe, sans redémarrage, plutôt qu'une mise à jour hors-ligne.
.TP
.B \-B,--nocacheupd
Pour ignorer la mise à jour forcée du cache de dnf.
.TP
.B \-0,--nolog
Pour détruire les logs.
.TP
.B \-p,--poweroff
Pour éteindre la machine après la mise à jour.
.TP
.B \-L,--changelog
Pour lister les modifications apportées par les mises à jour (RPM uniquement).
.TP
.B \-l,--limitlog
Pour ne conserver que les logs qui contiennent une mise à jour.
.TP
.B \-4,--forcednf4
Pour forcer l'utilisation de dnf v4 (par défaut la commande /usr/bin/dnf est utilisée).
.TP
.B \-5,--forcednf5
Pour forcer l'utilisation de dnf v5 (par défaut la commande /usr/bin/dnf est utilisée).
.TP
.B \-u,--distrupgrade
Pour monter en version (par exemple de Fc40 à Fc41).

.SH EXAMPLES
.PP
Pour vérifier si des mises à jour sont disponibles et informer l'utilisateur par une notification système

.B fedupdate \-n \-c

Pour contrôler les dépendances et afficher (ou re/créer) un fichier de configuration

.B fedupdate \-C

Pour faire une mise à jour des RPMs uniquement, en mode pseudo-silencieux, sans mettre à jour le cache de dnf et en utilisant dnf5

.B fedupdate \-FsB5


.SH NOTES
Le mode "contrôle de fonctionnement" (\fB-C\fR) va permettre de générer le fichier de configuration et de vérifier les dépendances.

Le fichier de configuration conserve le mail nécessaire à l'option \fB-m\fR et le mot de passe de l'utilisateur de \fBfedupdate\fR.

Ce mot de passe, utilisé par la commande \fBsudo\fR, peut-être stocké en clair, ou chiffré si la bibliothèque \fBopenssl\fR est installée.

Le mode "notification par email" (\fB-m\fR) et le mode "notification système" (\fB-n\fR) ne sont appliqués qu'en mode "vérification" (\fB-c\fR). Ils sont ignorés sinon.

Le mode "notification par email" (\fB-m\fR) n'est appliqué que si la commande est lancée en arrière plan (via une tâche cron ou une unité systemd).

Le mode "notification par email" (\fB-m\fR) nécessite la commande mail et un MTA configuré (Mail Transport Agent, comme \fBmsmtp\fR ou \fBopen\fR).

Une rotation des logs est effectuée à chaque exécution du programme.

9 logs RPMs et 9 logs FLATPAKs sont conservés au maximum. Les logs vides sont automatiquement supprimés.

Le mode "verbeux" (\fB-v\fR) permet d'outrepasser le mode "pseudo-silencieux" (\fB-s\fR) si ce dernier est activé par défaut dans le fichier config.rc.

Le mode -M permet d'outrepasser le mode -m si ce dernier est activé par défaut dans le fichier config.rc.

.SH FILES
.TP
.I $HOME/.config/fedupdate/config.rc
Fichier de configuration principal pour \fBfedupdate\fR.
.TP
.I $HOME/.local/share/fedupdate
Dossier des données de la commande \fBfedupdate\fR.

.SH AUTHOR
OLIVIER LORILLU

.SH COPYRIGHT
Copyright (C) OLIVIER LORILLU 2024. Ce script est distribué sous licence GPL v3.
